/*
 * Flink SQL Gateway REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2/1.18-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.jm.client.sql.gateway.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.jm.client.sql.gateway.invoker.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * ExecuteStatementResponseBody
 */

public class ExecuteStatementResponseBody {
  public static final String SERIALIZED_NAME_OPERATION_HANDLE = "operationHandle";
  @SerializedName(SERIALIZED_NAME_OPERATION_HANDLE)
  private String operationHandle;

  public ExecuteStatementResponseBody() {
  }

  public ExecuteStatementResponseBody operationHandle(String operationHandle) {
    this.operationHandle = operationHandle;
    return this;
  }

   /**
   * Get operationHandle
   * @return operationHandle
  **/
  //@javax.annotation.Nullable
  public String getOperationHandle() {
    return operationHandle;
  }

  public void setOperationHandle(String operationHandle) {
    this.operationHandle = operationHandle;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecuteStatementResponseBody executeStatementResponseBody = (ExecuteStatementResponseBody) o;
    return Objects.equals(this.operationHandle, executeStatementResponseBody.operationHandle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operationHandle);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecuteStatementResponseBody {\n");
    sb.append("    operationHandle: ").append(toIndentedString(operationHandle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("operationHandle");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ExecuteStatementResponseBody
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ExecuteStatementResponseBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExecuteStatementResponseBody is not found in the empty JSON string", ExecuteStatementResponseBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ExecuteStatementResponseBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ExecuteStatementResponseBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("operationHandle") != null && !jsonObj.get("operationHandle").isJsonNull()) && !jsonObj.get("operationHandle").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `operationHandle` to be a primitive type in the JSON string but got `%s`", jsonObj.get("operationHandle").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExecuteStatementResponseBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExecuteStatementResponseBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExecuteStatementResponseBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExecuteStatementResponseBody.class));

       return (TypeAdapter<T>) new TypeAdapter<ExecuteStatementResponseBody>() {
           @Override
           public void write(JsonWriter out, ExecuteStatementResponseBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ExecuteStatementResponseBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExecuteStatementResponseBody given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExecuteStatementResponseBody
  * @throws IOException if the JSON string is invalid with respect to ExecuteStatementResponseBody
  */
  public static ExecuteStatementResponseBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExecuteStatementResponseBody.class);
  }

 /**
  * Convert an instance of ExecuteStatementResponseBody to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

