/*
 * Flink SQL Gateway REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2/1.18-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.jm.client.sql.gateway.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.jm.client.sql.gateway.invoker.JSON;

import java.io.IOException;
import java.util.*;

/**
 * ExecuteStatementRequestBody
 */

public class ExecuteStatementRequestBody {
  public static final String SERIALIZED_NAME_EXECUTION_CONFIG = "executionConfig";
  @SerializedName(SERIALIZED_NAME_EXECUTION_CONFIG)
  private Map<String, String> executionConfig = new HashMap<>();

  public static final String SERIALIZED_NAME_EXECUTION_TIMEOUT = "executionTimeout";
  @SerializedName(SERIALIZED_NAME_EXECUTION_TIMEOUT)
  private Long executionTimeout;

  public static final String SERIALIZED_NAME_STATEMENT = "statement";
  @SerializedName(SERIALIZED_NAME_STATEMENT)
  private String statement;

  public ExecuteStatementRequestBody() {
  }

  public ExecuteStatementRequestBody executionConfig(Map<String, String> executionConfig) {
    this.executionConfig = executionConfig;
    return this;
  }

  public ExecuteStatementRequestBody putExecutionConfigItem(String key, String executionConfigItem) {
    if (this.executionConfig == null) {
      this.executionConfig = new HashMap<>();
    }
    this.executionConfig.put(key, executionConfigItem);
    return this;
  }

   /**
   * Get executionConfig
   * @return executionConfig
  **/
  //@javax.annotation.Nullable
  public Map<String, String> getExecutionConfig() {
    return executionConfig;
  }

  public void setExecutionConfig(Map<String, String> executionConfig) {
    this.executionConfig = executionConfig;
  }


  public ExecuteStatementRequestBody executionTimeout(Long executionTimeout) {
    this.executionTimeout = executionTimeout;
    return this;
  }

   /**
   * Get executionTimeout
   * @return executionTimeout
  **/
  //@javax.annotation.Nullable
  public Long getExecutionTimeout() {
    return executionTimeout;
  }

  public void setExecutionTimeout(Long executionTimeout) {
    this.executionTimeout = executionTimeout;
  }


  public ExecuteStatementRequestBody statement(String statement) {
    this.statement = statement;
    return this;
  }

   /**
   * Get statement
   * @return statement
  **/
  //@javax.annotation.Nullable
  public String getStatement() {
    return statement;
  }

  public void setStatement(String statement) {
    this.statement = statement;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecuteStatementRequestBody executeStatementRequestBody = (ExecuteStatementRequestBody) o;
    return Objects.equals(this.executionConfig, executeStatementRequestBody.executionConfig) &&
        Objects.equals(this.executionTimeout, executeStatementRequestBody.executionTimeout) &&
        Objects.equals(this.statement, executeStatementRequestBody.statement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(executionConfig, executionTimeout, statement);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecuteStatementRequestBody {\n");
    sb.append("    executionConfig: ").append(toIndentedString(executionConfig)).append("\n");
    sb.append("    executionTimeout: ").append(toIndentedString(executionTimeout)).append("\n");
    sb.append("    statement: ").append(toIndentedString(statement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("executionConfig");
    openapiFields.add("executionTimeout");
    openapiFields.add("statement");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ExecuteStatementRequestBody
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ExecuteStatementRequestBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExecuteStatementRequestBody is not found in the empty JSON string", ExecuteStatementRequestBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ExecuteStatementRequestBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ExecuteStatementRequestBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("statement") != null && !jsonObj.get("statement").isJsonNull()) && !jsonObj.get("statement").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `statement` to be a primitive type in the JSON string but got `%s`", jsonObj.get("statement").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExecuteStatementRequestBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExecuteStatementRequestBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExecuteStatementRequestBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExecuteStatementRequestBody.class));

       return (TypeAdapter<T>) new TypeAdapter<ExecuteStatementRequestBody>() {
           @Override
           public void write(JsonWriter out, ExecuteStatementRequestBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ExecuteStatementRequestBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExecuteStatementRequestBody given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExecuteStatementRequestBody
  * @throws IOException if the JSON string is invalid with respect to ExecuteStatementRequestBody
  */
  public static ExecuteStatementRequestBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExecuteStatementRequestBody.class);
  }

 /**
  * Convert an instance of ExecuteStatementRequestBody to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

