/*
 * Flink SQL Gateway REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2/1.18-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.jm.client.sql.gateway.model;

import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets ResultKind
 */
@JsonAdapter(ResultKind.Adapter.class)
public enum ResultKind {

    SUCCESS("SUCCESS"),

    SUCCESS_WITH_CONTENT("SUCCESS_WITH_CONTENT");

    private String value;

    ResultKind(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static ResultKind fromValue(String value) {
        for (ResultKind b : ResultKind.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ResultKind> {
        @Override
        public void write(final JsonWriter jsonWriter, final ResultKind enumeration) throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public ResultKind read(final JsonReader jsonReader) throws IOException {
            String value = jsonReader.nextString();
            return ResultKind.fromValue(value);
        }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        String value = jsonElement.getAsString();
        ResultKind.fromValue(value);
    }
}

